### ISSUE TITLE
Upgrade niapy version

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy-examples#18]
It has been a long time since we not received any updates in this repository. In fact, examples in this repo are compiled using the initial versions of niapy (app. 3 years ago).

Can anyone check the possibilities for upgrading this version of examples with the current niapy version?

@zStupan, what do you think?

**Comment by zStupan** [comment]
@firefly-cpp I updated the CLI for the CEC and CECC examples, but most of the CEC cython extensions won't build, because there are files missing or other make errors.
