### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by fglojnari** [NiaOrg/NiaPy-examples#9]
This line would always return values in range [40, 50], right? 
https://github.com/NiaOrg/NiaPy-examples/blob/e11c0d410da287292cb5f407d81ced7f0041e8df/optimize_KNN_parameters/run.py#L39

I would say it is `return int(val * 40 + 10)`

**Comment by GregaVrbancic** [comment]
Hi @fglojnari!

Thank you for reporting the issue. Of course, the right definition is as you mentioned ```return int(val * 40 + 10)```. The issue has been already resolved in PR #10
